console.log('\n***********\nESNEXT - set- 8ª aula \n*****************\n')
const times = new Set()
times.add('Corinthians')
console.log(times)
times.add('Vasco').add('São Paulo').add('Flamengo').add('Palmeiras')
console.log(times.size)
console.log(times)
console.log(times.has('São Paulo'))
times.delete('São Paulo')
console.log(times.has('São Paulo'))
times.add('Corinthians')
console.log(times)